export const COMMUNITY_SERVICE_CREATE_REQUEST = 'COMMUNITY_SERVICE_CREATE_REQUEST'
export const COMMUNITY_SERVICE_CREATE_SUCCESS = 'COMMUNITY_SERVICE_CREATE_SUCCESS'
export const COMMUNITY_SERVICE_CREATE_FAIL = 'COMMUNITY_SERVICE_CREATE_FAIL'
export const COMMUNITY_SERVICE_CREATE_RESET = 'COMMUNITY_SERVICE_CREATE_RESET'


export const COMMUNITY_SERVICE_LIST_REQUEST = 'COMMUNITY_SERVICE_LIST_REQUEST'
export const COMMUNITY_SERVICE_LIST_SUCCESS = 'COMMUNITY_SERVICE_LIST_SUCCESS'
export const COMMUNITY_SERVICE_LIST_FAIL = 'COMMUNITY_SERVICE_LIST_FAIL'
export const COMMUNITY_SERVICE_LIST_ADD = 'COMMUNITY_SERVICE_LIST_ADD'


export const COMMUNITY_SERVICE_DELETE_REQUEST = 'COMMUNITY_SERVICE_DELETE_REQUEST'
export const COMMUNITY_SERVICE_DELETE_SUCCESS = 'COMMUNITY_SERVICE_DELETE_SUCCESS'
export const COMMUNITY_SERVICE_DELETE_FAIL = 'COMMUNITY_SERVICE_DELETE_FAIL'


export const COMMUNITY_SERVICE_DETAILS_REQUEST = 'COMMUNITY_SERVICE_DETAILS_REQUEST'
export const COMMUNITY_SERVICE_DETAILS_SUCCESS = 'COMMUNITY_SERVICE_DETAILS_SUCCESS'
export const COMMUNITY_SERVICE_DETAILS_FAIL = 'COMMUNITY_SERVICE_DETAILS_FAIL'


export const COMMUNITY_SERVICE_UPDATE_REQUEST = 'COMMUNITY_SERVICE_UPDATE_REQUEST'
export const COMMUNITY_SERVICE_UPDATE_SUCCESS = 'COMMUNITY_SERVICE_UPDATE_SUCCESS'
export const COMMUNITY_SERVICE_UPDATE_FAIL = 'COMMUNITY_SERVICE_UPDATE_FAIL'
export const COMMUNITY_SERVICE_UPDATE_RESET = 'COMMUNITY_SERVICE_UPDATE_RESET'