export const DISPUTE_CREATE_REQUEST = 'DISPUTE_CREATE_REQUEST'
export const DISPUTE_CREATE_SUCCESS = 'DISPUTE_CREATE_SUCCESS'
export const DISPUTE_CREATE_FAIL = 'DISPUTE_CREATE_FAIL'
export const DISPUTE_CREATE_RESET = 'DISPUTE_CREATE_RESET'

export const DISPUTE_UPDATE_REQUEST = 'DISPUTE_UPDATE_REQUEST'
export const DISPUTE_UPDATE_SUCCESS = 'DISPUTE_UPDATE_SUCCESS'
export const DISPUTE_UPDATE_FAIL = 'DISPUTE_UPDATE_FAIL'
export const DISPUTE_UPDATE_RESET = 'DISPUTE_UPDATE_RESET'

export const DISPUTE_IS_SELLER_SERVICE_REQUEST = 'DISPUTE_IS_SELLER_SERVICE_CREATE_REQUEST'
export const DISPUTE_IS_SELLER_SERVICE_CREATE_SUCCESS = 'DISPUTE_IS_SELLER_SERVICE_CREATE_SUCCESS'
export const DISPUTE_IS_SELLER_SERVICE_CREATE_FAIL = 'DISPUTE_IS_SELLER_SERVICE_CREATE_FAIL'
export const DISPUTE_IS_SELLER_SERVICE_CREATE_RESET = 'DISPUTE_IS_SELLER_SERVICE_CREATE_RESET'

export const DISPUTES_GET_REQUEST = 'DISPUTES_GET_REQUEST'
export const DISPUTES_GET_SUCCESS = 'DISPUTES_GET_SUCCESS'
export const DISPUTES_GET_FAIL = 'DISPUTES_GET_FAIL'
export const DISPUTES_GET_RESET = 'DISPUTES_GET_RESET'


export const DISPUTE_GET_REQUEST = 'DISPUTE_GET_REQUEST'
export const DISPUTE_GET_SUCCESS = 'DISPUTE_GET_SUCCESS'
export const DISPUTE_GET_FAIL = 'DISPUTE_GET_FAIL'
export const DISPUTE_GET_RESET = 'DISPUTE_GET_RESET'


export const IF_IN_DISPUTES_GET_REQUEST = 'IF_IN_DISPUTES_GET_REQUEST'
export const IF_IN_DISPUTES_GET_SUCCESS = 'IF_IN_DISPUTES_GET_SUCCESS'
export const IF_IN_DISPUTES_GET_FAIL = 'IF_IN_DISPUTES_GET_FAIL'
export const IF_IN_DISPUTES_GET_RESET = 'IF_IN_DISPUTES_GET_RESET'