export const PAID_SERVICE_CREATE_REQUEST = 'PAID_SERVICE_CREATE_REQUEST'
export const PAID_SERVICE_CREATE_SUCCESS = 'PAID_SERVICE_CREATE_SUCCESS'
export const PAID_SERVICE_CREATE_FAIL = 'PAID_SERVICE_CREATE_FAIL'
export const PAID_SERVICE_CREATE_RESET = 'PAID_SERVICE_CREATE_RESET'


export const PAID_SERVICES_LIST_REQUEST = 'PAID_SERVICES_LIST_REQUEST'
export const PAID_SERVICES_LIST_SUCCESS = 'PAID_SERVICES_LIST_SUCCESS'
export const PAID_SERVICES_LIST_FAIL = 'PAID_SERVICES_LIST_FAIL'
export const PAID_SERVICES_LIST_ADD = 'PAID_SERVICES_LIST_ADD'


export const PAID_SERVICES_DELETE_REQUEST = 'PAID_SERVICE_DELETE_REQUEST'
export const PAID_SERVICES_DELETE_SUCCESS = 'PAID_SERVICE_DELETE_SUCCESS'
export const PAID_SERVICES_DELETE_FAIL = 'PAID_SERVICE_DELETE_FAIL'


export const PAID_SERVICE_DETAILS_REQUEST = 'PAID_SERVICE_DETAILS_REQUEST'
export const PAID_SERVICE_DETAILS_SUCCESS = 'PAID_SERVICE_DETAILS_SUCCESS'
export const PAID_SERVICE_DETAILS_FAIL = 'PAID_SERVICE_DETAILS_FAIL'


export const PAID_SERVICE_UPDATE_REQUEST = 'PAID_SERVICE_UPDATE_REQUEST'
export const PAID_SERVICE_UPDATE_SUCCESS = 'PAID_SERVICE_UPDATE_SUCCESS'
export const PAID_SERVICE_UPDATE_FAIL = 'PAID_SERVICE_UPDATE_FAIL'
export const PAID_SERVICE_UPDATE_RESET = 'PAID_SERVICE_UPDATE_RESET'