export const RENT_CREATE_REQUEST = 'RENT_CREATE_REQUEST'
export const RENT_CREATE_SUCCESS = 'RENT_CREATE_SUCCESS'
export const RENT_CREATE_FAIL = 'RENT_CREATE_FAIL'
export const RENT_CREATE_RESET = 'RENT_CREATE_RESET'


export const RENT_LIST_REQUEST = 'RENT_LIST_REQUEST'
export const RENT_LIST_SUCCESS = 'RENT_LIST_SUCCESS'
export const RENT_LIST_FAIL = 'RENT_LIST_FAIL'
export const RENT_LIST_ADD = 'RENT_LIST_ADD'


export const RENT_DELETE_REQUEST = 'RENT_DELETE_REQUEST'
export const RENT_DELETE_SUCCESS = 'RENT_DELETE_SUCCESS'
export const RENT_DELETE_FAIL = 'RENT_DELETE_FAIL'
export const RENT_DELETE_RESET = 'RENT_DELETE_RESET'



export const RENT_DETAILS_REQUEST = 'RENT_DETAILS_REQUEST'
export const RENT_DETAILS_SUCCESS = 'RENT_DETAILS_SUCCESS'
export const RENT_DETAILS_FAIL = 'RENT_DETAILS_FAIL'


export const RENT_UPDATE_REQUEST = 'RENT_UPDATE_REQUEST'
export const RENT_UPDATE_SUCCESS = 'RENT_UPDATE_SUCCESS'
export const RENT_UPDATE_FAIL = 'RENT_UPDATE_FAIL'
export const RENT_UPDATE_RESET = 'RENT_UPDATE_RESET'